name: Parent workflow

on:
  workflow_dispatch:
    inputs:
      Release_Version:
        type: string
        required: true
      Model_Type:
        type: string
        required: true

jobs:
  set_variable:
    name: set_variable
    runs-on: ubuntu-latest
    steps:
      - name: set_variable
        id: set_variable
        run: |
          echo  $!
          echo  $!
  
